# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Bank
# Author: https://www.mc-market.org/members/89497/ | https://www.spigotmc.org/members/radekjenejlepsi.227786/
# Description: Plugin for in-game Bank
# Dependencies:
#   -> PLJRApi
#   -> MySQL
#   -> Vault (https://www.spigotmc.org/resources/vault.34315/)
#   -> PlaceholderAPI<Optional> (https://www.spigotmc.org/resources/placeholderapi.6245/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  banks-menu-change-current: true #-> Should we change the current tier of bank to player's head?
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# Banks Setup ###################################\
############### Here, you can setup bank tiers. # \
              ###################################  \
banks:
  default:
    max: 100000
    cost: 0
    perm: ""
  tier-2:
    max: 200000
    cost: 50000
    perm: "bank.tier.2"
  tier-3:
    max: 300000
    cost: 100000
    perm: "bank.tier.3"
  tier-4:
    max: 400000
    cost: 200000
    perm: "bank.tier.4"
  tier-5:
    max: 500000
    cost: 250000
    perm: "bank.tier.5"

#|--------------------------------------------------------------------------------------------------------------------|#
###############\
# Menus Setup ###########################################################\
############### Here, you can customize the looks of all in-game menus. # \
              ###########################################################  \
main-menu:
  title: "§b§lBanka"
  background:
    type: "BLACK_STAINED_GLASS_PANE"
    name: "§0"
    amount: 1
    lore:
      - "§r"
  head:
    head: true
    head-owner: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDY3ZGNlNDY0NTM0OWU0MWE3ZjM1Nzk3ZTJiOTI3OWUzNWE2NWY1ZTgxYTM0NDk2ODg1ZDI3MjY4ZjM2OTEzOSJ9fX0="
    amount: 1
    name: "§a§lBANKA"
    lore:
      - "§8► §7%amount§8/§7%max"
      - ""
      - "§eKlikni §fpro změnu banky."
  withdraw:
    type: "BUCKET"
    name: "§e§lVYBRAT"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání financí z banky."
  deposit:
    type: "WATER_BUCKET"
    name: "§e§lVLOŽIT"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení financí do banky."

deposit-menu:
  title: "§b§lBanka - Vklad"
  background:
    type: "BLACK_STAINED_GLASS_PANE"
    name: "§0"
    amount: 1
    lore:
      - "§r"
  add-10:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a10"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e10$"
  add-100:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a100"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e100$"
  add-1000:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a1000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e1000$"
  add-10000:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a10000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e10000$"
  add-100000:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a100000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e100000"
  add-1000000:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a1000000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e1000000"
  add-10000000:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a10000000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e10000000"
  add-100000000:
    type: "LIME_STAINED_GLASS_PANE"
    name: "§a§lPŘIDAT §a100000000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §e100000000"
  add-all:
    type: "LIME_STAINED_GLASS"
    name: "§a§lPŘIDAT §aVŠECHNO"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §eVŠECH §ftvých peněz do banky."
  add-custom:
    type: "COMMAND_BLOCK"
    name: "§a§lPŘIDAT §aVlastní Častku"
    amount: 1
    lore:
      - "§8► §fKlikni pro vložení §evlastní §fčástky do banky."


withdraw-menu:
  title: "§b§lBanka - Výběr"
  background:
    type: "BLACK_STAINED_GLASS_PANE"
    name: "§0"
    amount: 1
    lore:
      - "§r"
  remove-10:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c10"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e10$"
  remove-100:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c100"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e100$"
  remove-1000:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c1000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e1000$"
  remove-10000:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c10000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e10000$"
  remove-100000:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c100000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e100000"
  remove-1000000:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c1000000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e1000000"
  remove-10000000:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c10000000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e10000000"
  remove-100000000:
    type: "RED_STAINED_GLASS_PANE"
    name: "§c§lODEBRAT §c100000000"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §e100000000"
  remove-all:
    type: "RED_STAINED_GLASS"
    name: "§c§lODEBRAT §cVŠECHNO"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §eVŠECH §ffinančních prostředků z banky."
  remove-custom:
    type: "COMMAND_BLOCK"
    name: "§c§lODEBRAT §cVlastní Částku"
    amount: 1
    lore:
      - "§8► §fKlikni pro vybrání §evlastní §fčástky z banky."

banks-menu:
  title: "§b§lBanka - Typ"
  background:
    type: "BLACK_STAINED_GLASS_PANE"
    name: "§0"
    amount: 1
    lore:
      - "§r"
  type-default:
    type: "SOUL_SAND"
    name: "§7§lBĚŽNÝ §7Účet"
    amount: 1
    lore:
      - "§7Max. Vložení §8► §f%max"
  type-2:
    type: "DIRT"
    name: "§f§lOBYČEJNÝ §fÚčet"
    amount: 1
    lore:
      - "§7Max. Vložení  §8► §f%max"
      - "§7Cena §8► §f%cost"
      - "§7Lze zakoupit §8► §f%perm"
  type-3:
    type: "GRASS"
    name: "§e§lNEOBYČEJNÝ §eÚčet"
    amount: 1
    lore:
      - "§7Max. Vložení  §8► §f%max"
      - "§7Cena §8► §f%cost"
      - "§7Lze zakoupit §8► §f%perm"
  type-4:
    type: "CHEST"
    name: "§b§lEPICKÝ §bÚčet"
    amount: 1
    lore:
      - "§7Max. Vložení  §8► §f%max"
      - "§7Cena §8► §f%cost"
      - "§7Lze zakoupit §8► §f%perm"
  type-5:
    type: "ENDER_CHEST"
    name: "§d§lLEGENDÁRNÍ §dÚčet"
    amount: 1
    lore:
      - "§7Max. Vložení  §8► §f%max"
      - "§7Cena §8► §f%cost"
      - "§7Lze zakoupit §8► §f%perm"

#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Lang Setup ################################################################\
############## Here, you can customize messages, send by the plugin itself. # \
             ################################################################  \

help:
  - ""
  - "§a§lBank Help"
  - ""
  - "§e/bank §8» §fOtevře hlavní menu."
  - "§e/bank help §8» §fZobrazí tuto zprávu."
  - "§e/bank add <množství> §8» §fVloží částku do banky."
  - "§e/bank addall §8» §fVloží všechny peníze do banky."
  - "§e/bank remove <množství> §8» §fVybere částku z banky."
  - "§e/bank removeall §8» §fVybere všechny peníze z banky."
  - "§e/bank show <hráč> §8» §fZobrazí hráčovi informace."

admin-help:
  - ""
  - "§a§lBank Admin-Help"
  - ""
  - "§e/abank set <hráč> <množství> §8» §fNastaví množství zůstatku v bance hráče. §7(Ignoruje Úroveň)"
  - "§e/abank add <hráč> <množství> §8» §fPřidá množství do banky hráče. §7(Ignoruje Úroveň)"
  - "§e/abank remove <hráč> <množství> §8» §fOdebere množství z banky hráče."

deposit-message:
  - ""
  - "§e§lBANKA"
  - "<click:suggest_command:'/bank add '>§8» §fKlikni na tuto zprávu pro §evložení §fvlastní částky do banky.</click>"
  - ""

withdraw-message:
  - ""
  - "§e§lBANKA"
  - "<click:suggest_command:'/bank remove '>§8» §fKlikni na tuto zprávu pro §eodebrání §fvlástní částky z banky.</click>"
  - ""

lang:
  NO_CONSOLE: "§cTento příkaz je pouze pro herní použití!"
  ADD_SUCCESS: "§aBank §8» §b%money §fbylo vloženo do Vašeho účtu."
  ADD_FAILURE_TOO_MUCH: "§aBank §8» §fNemůžete přidat §b%money §fdo Vašeho účtu!"
  ADD_FAILURE_NOT_ENOUGH: "§aBank §8» §fNemáte dostatek financí pro tuto akci!"
  REMOVE_SUCCESS: "§aBank §8» §fÚspěšně vybráno §b%money §fz Vaší banky."
  REMOVE_FAILURE_TOO_MUCH: "§aBank §8» §fNemáte dostatek financí ve Vaší bance!"
  SHOW_PLAYER: "§aBank §8» §b%player §fmá na kontě $§b%amount§f"
  PERM_YES: "§aAno"
  PERM_NO: "§cNe"
  BUY_SUCCESS: "§aBank §8» §fÚspěšně jste zakoupil/a nový §bbankovní účet§f!"
  BUY_FAILURE: "§aBank §8» §fNemáte dostatek financí pro zakoupení tohoto účtu!"
  NO_POSITIVE: "§aBank §8» §fČíslo musí být positivní!"
  ADMIN_SET_SUCCESS: "§aBank §8» §fZůstatek hráče/ky §b%player §fbyl nastaven na §b%money§f."
  ADMIN_SET_SUCCESS_NOTIFY: "§aBank §8» §fVáš účetní zůstatek byl nastaven na §b%money §fadminem/kou §b%player§f."
  ADMIN_ADD_SUCCESS: "§aBank §8» §fÚspěšně přidáno §b%money §fna bankovní účet hráče/ky §b%player§f."
  ADMIN_ADD_SUCCESS_NOTIFY: "§aBank §8» §b%money §fbylo přidáno na Váš bankovní účet adminem/kou §b%player§f."
  ADMIN_REMOVE_SUCCESS: "§aBank §8» §fÚspěšně odebráno §b%money §fz bankovního účetu hráče/ky §b%player§f."
  ADMIN_REMOVE_FAILURE_TOO_MUCH: "§aBank §8» §b%player §fnemá dostatek financí v bance!"
  ADMIN_REMOVE_SUCCESS_NOTIFY: "§aBank §8» §b%money §fbylo odebráno z Vaší banky adminem/kou §b%player§f."
#|--------------------------------------------------------------------------------------------------------------------|#
