# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: Economy
# Author: https://www.mc-market.org/members/89497/
# Description: Plugin for handling in-game economy.
# Dependencies:
#   -> MySQL Database
#   -> PLJRApi
#   -> Vault (https://www.spigotmc.org/resources/vault.34315/)
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Lang Setup ################################################################\
############## Here, you can customize messages, send by the plugin itself. # \
             ################################################################  \

help:
  - ""
  - "§a§lEconomy"
  - ""
  - "§e/economy §8» §7Zobrazí Váš aktuální zůstatek."
  - "§e/economy help §8» §7Zobrazí tuto zprávu."
  - "§e/economy balance <hráč> §8» §7Zobrazí aktuální zůstatek hráče."
  - "§e/economy send <hráč> <množství> §8» §7Odešle hráči/ce určité množství financí."

admin-help:
  - ""
  - "§a§lEconomy Admin"
  - ""
  - "§e/aeconomy help §8» §7Zobrazí tuto zprávu."
  - "§e/aeconomy set <hráč> <množství> §8» §7Nastaví zůstatek hráče/ky."
  - "§e/aeconomy add <hráč> <množství> §8» §7Přidá hráči/ce určité množství financí."
  - "§e/aeconomy remove <hráč> <množství> §8» §7Odebere hráči/ce určité množství financí."

lang:
  CONSOLE_NAME: "Konzole"
  NO_POSITIVE_NUMBER: "§aEconomy §8» §7Číslo musí být positivní!"
  ECONOMY_SUCCESS: "§aEconomy §8» §7Váš zůstatek činí: §6${money}§7."
  ECONOMY_BALANCE_SUCCESS: "§aEconomy §8» §7Zůstatek hráče/ky §6{player} §7činí: §6${money}§7."
  ECONOMY_SEND_SUCCESS: "§aEconomy §8» §7Úspěšně odesláno §6{money} §7hráči/ce §6{player}§7."
  ECONOMY_SEND_FAILURE_TOO_MUCH: "§aEconomy §8» §7Nemáte dostatek financí!"
  ECONOMY_SEND_SUCCESS_NOTIFY: "§aEconomy §8» §7Obdrželi jste §6${money} §7od §6{player}§7."
  AECONOMY_SET_SUCCESS: "§aEconomy §8» §7Úspěšně jste nastavili zůstatek hráče/ky §6{player} §7na §6${money}§7."
  AECONOMY_SET_SUCCESS_NOTIFY: "§aEconomy §8» §7Váš zůstatek byl nastaven na §6${money}§7."
  AECONOMY_ADD_SUCCESS: "§aEconomy §8» §7Úspěšně jste přidali §6${money} §7hráči/ce §6{player}§7."
  AECONOMY_ADD_SUCCESS_NOTIFY: "§aEconomy §8» §6${money} §7bylo přidáno na Váš účet."
  AECONOMY_REMOVE_SUCCESS: "§aEconomy §8» §7Úspěšně jste odebráli §6${money} §7z účtu hráče/ky §6{player}§7."
  AECONOMY_REMOVE_FAILURE_TOO_MUCH: "§aEconomy §8» §6{player} §7nemá dostatek financí!"
  AECONOMY_REMOVE_SUCCESS_NOTIFY: "§aEconomy §8» §6${money} §7bylo odebráno z Vašeho účtu."

  # Vault responses, they are not shown in commands, but you can still customize them and use in your plugin perhaps.
  VAULT_WITHDRAW_PLAYER_FAILURE_NO_ACCOUNT: "§c{player} does not have an account!"
  VAULT_WITHDRAW_PLAYER_FAILURE_TOO_MUCH: "§c{player} does not have enough money."
  VAULT_DEPOSIT_PLAYER_FAILURE_NO_ACCOUNT: "§c{player} does not have an account!"
  VAULT_NOT_IMPLEMENTED: "§cThis functions is not implemented!"
#|--------------------------------------------------------------------------------------------------------------------|#