# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: KillStreak
# Author: https://www.mc-market.org/members/89497/ | https://www.spigotmc.org/members/radekjenejlepsi.227786/
# Description: Simple plugin for counting kills of players.
# Dependencies:
#   -> PLJRApi
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false #-> Should we use this database instead of the one configured in PLJRApi config.yml?
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##################\
# Settings Setup #############################################################\
################## Here, you can enable or disable functions of this plugin. # \
                 #############################################################  \
settings:
  bungee: false #-> Should we use bungee functions?
  leaderboard: 15 #-> How many players should be displayed in the menu? (Minimum is 3)
  autoupdate: 3600 #-> Time between automatic updates of leader board. (In seconds)
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Menu Setup ###############################################\
############## Here, you can customize plugin's main menu. # \
             ###############################################  \
menu:
  top1:
    name: "&e1. &7%name"
    lore:
      - "&8► §7%kills"
  top2:
    name: "&e2. &7%name"
    lore:
      - "&8► §7%kills"
  top3:
    name: "&e3. &7%name"
    lore:
      - "&8► §7%kills"
  leaderboard:
    type: "SIGN"
    name: "&eOstatní"
    amount: 1
  update:
    type: "REDSTONE"
    name: "&aAktualizovat"
    amount: 1
    lore:
      - "&8► &fKlikni pro aktualizaci."
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Lang Setup ################################################################\
############## Here, you can customize messages, send by the plugin itself. # \
             ################################################################  \
lang:
  MENU_TITLE: "&8&lKillStreak"
  LEADERBOARD_FORMAT: "&8► &e%pos. &7%name &f%kills"
  NO_CONSOLE: "&aKillStreak &8» &fTento příkaz je pouze pro herní použití!"
#|--------------------------------------------------------------------------------------------------------------------|#

#####################
# KillStreaks Setup ####################################################################
##################### Here, you can create and customize your own special killstreaks! #
                    ####################################################################
killstreaks:
  default:
    start: 0
    end: 99
    broadcast: false
    broadcast-message:
      - "Noone will ever see this! Haha!"
    title:
      title: "&c&lKillStreak"
      subtitle: "&fTvá serie zabití je nyní &e%killstreak&f!"
      in: 20
      stay: 40
      out: 20
    sound:
      type: "BLOCK_ANVIL_BREAK"
      volume: 1
      pitch: 1
  
  special-example:
    start: 100
    end: 100
    broadcast: true
    broadcast-message:
      - ""
      - "§e§lKILLSTREAK"
      - "§c%killer §7zabil §c%victim§7!"
      - "§7Jeho série zabití je nyní neskutečných §6100 §7zabití!"
      -
    title:
      title: "&e&lKillStreak"
      subtitle: "&fTvá serie zabití je nyní §6§l%killstreak&f!"
      in: 20
      stay: 50
      out: 20
    sound:
      type: "BLOCK_ANVIL_BREAK"
      volume: 1
      pitch: 1
  
  infinite:
    start: 101
    end: 9999
    broadcast: false
    broadcast-message:
      - "Noone will ever see this! Haha!"
    title:
      title: "&c&lKillStreak"
      subtitle: "&fTvá serie zabití je nyní &e%killstreak&f!"
      in: 20
      stay: 40
      out: 20
    sound:
      type: "BLOCK_ANVIL_BREAK"
      volume: 1
      pitch: 1
  
#|--------------------------------------------------------------------------------------------------------------------|#